"""Tests for the standalone-flow orchestrator."""

from __future__ import annotations

import re
from datetime import datetime
from io import StringIO
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

from webtrees_installer.cli import build_parser
from webtrees_installer.flow import (
    StandaloneArgs,
    _list_surviving_volumes as real_list_surviving_volumes,
    _wipe_volumes as real_wipe_volumes,
    run_standalone,
)
from webtrees_installer.prompts import PromptError
from webtrees_installer.ports import PortStatus
from webtrees_installer.prereq import PrereqError
from webtrees_installer.versions import Catalog, PhpEntry


_TEST_CATALOG = Catalog(
    php_entries=(
        PhpEntry(webtrees="2.2.6", php="8.5", tags=("latest",)),
    ),
    nginx_tag="1.30-r1",
    installer_version="0.1.0",
)


@pytest.fixture(autouse=True)
def silence_prereq_and_docker(tmp_path_factory, monkeypatch) -> None:
    """Stub prereq check, load_catalog and the docker volume pre-seed so
    flow tests stay hermetic and never invoke real docker.

    WEBTREES_INSTALLER_MANIFEST_DIR is pointed at a real (empty) directory
    so ``_resolve_manifest_dir`` succeeds; ``load_catalog`` is mocked, so
    the empty directory is never actually read. Tests that need to
    exercise ``_resolve_manifest_dir`` itself unset the env var via their
    own monkeypatch.
    """
    fake_manifest = tmp_path_factory.mktemp("fake_manifest")
    monkeypatch.setenv("WEBTREES_INSTALLER_MANIFEST_DIR", str(fake_manifest))
    with patch("webtrees_installer.flow.check_prerequisites"), \
         patch("webtrees_installer.flow.load_catalog", return_value=_TEST_CATALOG), \
         patch("webtrees_installer.flow._write_admin_password_secret"), \
         patch("webtrees_installer.flow._list_surviving_volumes", return_value=[]):
        yield


def _args(**overrides) -> StandaloneArgs:
    """Build a StandaloneArgs with non-interactive defaults that exercise the happy path."""
    defaults = dict(
        work_dir=None,
        interactive=False,
        edition="full",
        proxy_mode="standalone",
        app_port=8080,
        domain=None,
        traefik_network="traefik",
        admin_bootstrap=True,
        admin_user="admin",
        admin_email="admin@example.org",
        demo=False,
        demo_seed=42,
        enforce_https=True,
        pretty_urls=False,
        force=True,
        no_up=True,
    )
    defaults.update(overrides)
    return StandaloneArgs(**defaults)


def test_run_standalone_writes_compose_and_env(tmp_path: Path) -> None:
    args = _args(work_dir=tmp_path)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        exit_code = run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert exit_code == 0
    assert (tmp_path / "compose.yaml").is_file()
    assert (tmp_path / ".env").is_file()

    compose = yaml.safe_load((tmp_path / "compose.yaml").read_text())
    assert "/php-full:" in compose["services"]["phpfpm"]["image"]


def test_run_standalone_reveals_admin_password(tmp_path: Path) -> None:
    args = _args(work_dir=tmp_path)
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "admin" in body
    assert re.search(r"[0-9a-f]{24}", body), body
    assert "╔" in body and "╚" in body, "credentials should be inside an ASCII box"
    assert "webtrees admin credentials" in body
    assert "redact before sharing" in body
    assert "autogenerated" in body
    assert "rotate after first login" in body.lower()
    assert "not saved to disk" in body
    # Banner-only policy: no file path leak in the operator-facing copy.
    assert ".webtrees-admin-password" not in body


def test_run_standalone_no_admin_hides_credentials_box(tmp_path: Path) -> None:
    args = _args(
        work_dir=tmp_path,
        admin_bootstrap=False,
        admin_user=None,
        admin_email=None,
    )
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "webtrees admin credentials" not in body
    assert "autogenerated" not in body
    assert "rotate after first login" not in body.lower()
    assert "not saved to disk" not in body


def test_run_standalone_emits_gha_mask_when_running_under_github_actions(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    # The smoke job runs the installer on a public-repo runner; without an
    # explicit ::add-mask:: directive the autogenerated password lands
    # verbatim in the run log. Verify the directive precedes the credentials
    # block when GITHUB_ACTIONS=true.
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    args = _args(work_dir=tmp_path)
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    match = re.search(r"::add-mask::([0-9a-f]{24,})", body)
    assert match is not None, body
    masked_password = match.group(1)
    # The masked password must be the same string that appears inside the
    # credentials box — otherwise the directive masks nothing useful.
    assert masked_password in body
    # The directive must precede the password value's first non-directive
    # occurrence (the "password:" row inside the box) — otherwise the runner
    # has already emitted the secret by the time it learns to mask it.
    mask_pos = body.index(f"::add-mask::{masked_password}")
    password_cell_pos = body.index(f"password:  {masked_password}")
    assert mask_pos < password_cell_pos
    # Single-line directive: a stray newline inside the value would split
    # the line and break GHA's parser. The mask-line is the entire match.
    assert re.search(r"^::add-mask::[0-9a-f]{24,}$", body, re.MULTILINE)


def test_run_standalone_omits_gha_mask_outside_github_actions(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("GITHUB_ACTIONS", raising=False)
    args = _args(work_dir=tmp_path)
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "::add-mask::" not in body


def test_run_standalone_no_admin_under_gha_emits_no_mask(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    # The mask directive is gated on admin_user; --no-admin must not emit
    # ::add-mask::None even when GITHUB_ACTIONS=true. A future maintainer
    # who hoists the directive out of the credentials block for symmetry
    # would silently emit the literal "None" — this test pins that.
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    args = _args(
        work_dir=tmp_path,
        admin_bootstrap=False,
        admin_user=None,
        admin_email=None,
    )
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "::add-mask::" not in body


def test_run_standalone_ignores_admin_user_when_bootstrap_off(
    tmp_path: Path,
) -> None:
    # cli.py forwards args.admin_user to StandaloneArgs unconditionally.
    # Inside run_standalone, the credentials banner is suppressed because
    # admin_bootstrap=False short-circuits the username/password block.
    # Pin that invariant so a future refactor that forwards admin_user
    # straight into the banner doesn't reintroduce a None-password row.
    args = _args(
        work_dir=tmp_path,
        admin_bootstrap=False,
        admin_user="rico",
        admin_email="rico@example.org",
    )
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "webtrees admin credentials" not in body
    assert "rico" not in body


def test_run_standalone_custom_admin_user_keeps_autogen_password(
    tmp_path: Path,
) -> None:
    args = _args(work_dir=tmp_path, admin_user="rico")
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "user:      rico" in body
    assert re.search(r"password:  [0-9a-f]{24,}", body), body
    assert "autogenerated" in body


def test_no_admin_password_cli_flag_exists() -> None:
    # The banner's "autogenerated" claim relies on the invariant that the
    # password is always generate_password()'d, never operator-supplied.
    # Adding --admin-password without revisiting the banner would silently
    # turn that claim into a lie.
    parser = build_parser()
    with pytest.raises(SystemExit):
        parser.parse_args(["--admin-password", "x"])


def test_run_standalone_warns_on_surviving_volumes_non_interactive(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "myproj")
    args = _args(work_dir=tmp_path)
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow._list_surviving_volumes",
               return_value=["myproj_database", "myproj_secrets"]), \
         patch("webtrees_installer.flow._wipe_volumes") as wipe:
        run_standalone(args, stdin=StringIO(), stdout=out)

    body = out.getvalue()
    assert "existing docker volumes" in body.lower()
    assert "myproj_database" in body
    assert "myproj_secrets" in body
    # The exact cleanup commands must be copy-paste-ready in the output:
    # compose down first (so the volumes are unlocked) then a single
    # docker volume rm with all names.
    assert "docker compose -p myproj down" in body
    assert "docker volume rm myproj_database myproj_secrets" in body
    # Non-interactive must NEVER auto-delete data.
    wipe.assert_not_called()


def test_run_standalone_offers_wipe_interactively_and_keeps_on_no(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "myproj")
    args = _args(work_dir=tmp_path, interactive=True, force=True)
    # ask_yesno reads stdin; an empty input keeps the default (False = keep).
    stdin = StringIO("")
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow._list_surviving_volumes",
               return_value=["myproj_database"]), \
         patch("webtrees_installer.flow._wipe_volumes") as wipe:
        run_standalone(args, stdin=stdin, stdout=out)

    body = out.getvalue()
    assert "Wipe them now" in body
    assert "Keeping existing volumes" in body
    # Even on the "keep" path the operator should see the exact commands
    # they would need to clean up later.
    assert "docker compose -p myproj down" in body
    assert "docker volume rm myproj_database" in body
    wipe.assert_not_called()


def test_run_standalone_wipes_when_interactive_user_answers_yes(tmp_path: Path) -> None:
    args = _args(work_dir=tmp_path, interactive=True, force=True)
    # `y` confirms the prompt; downstream prompts get empty lines.
    stdin = StringIO("y\n")
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow._list_surviving_volumes",
               return_value=["test_database", "test_secrets"]), \
         patch("webtrees_installer.flow._wipe_volumes") as wipe:
        run_standalone(args, stdin=stdin, stdout=out)

    wipe.assert_called_once_with(["test_database", "test_secrets"])
    assert "Wiped 2 stale volume(s)" in out.getvalue()


def test_run_standalone_no_volume_prompt_when_none_survive(tmp_path: Path) -> None:
    args = _args(work_dir=tmp_path, interactive=True)
    out = StringIO()
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow._list_surviving_volumes", return_value=[]), \
         patch("webtrees_installer.flow._wipe_volumes") as wipe:
        run_standalone(args, stdin=StringIO(), stdout=out)

    assert "existing docker volumes" not in out.getvalue().lower()
    wipe.assert_not_called()


def test_run_standalone_rejects_no_https_when_traefik_chosen_at_prompt(
    tmp_path: Path,
) -> None:
    """Interactive bypass guard: cli.py validates --no-https + --proxy traefik
    only when both flags are passed. If the operator passes only --no-https
    and selects 'traefik' at the proxy prompt, the CLI check sees
    args.proxy_mode is None and skips — flow.py must catch the inconsistent
    combo after the prompt resolves."""
    args = _args(
        work_dir=tmp_path,
        interactive=True,
        proxy_mode=None,
        enforce_https=False,
        domain="webtrees.example.com",
    )
    out = StringIO()
    with patch(
        "webtrees_installer.flow.ask_choice",
        side_effect=["full", "traefik"],
    ), pytest.raises(PromptError) as exc_info:
        run_standalone(args, stdin=StringIO(), stdout=out)

    msg = str(exc_info.value)
    assert "--no-https" in msg
    assert "traefik" in msg
    assert "standalone" in msg
    # Pin the shared "why" clause from prompts.TRAEFIK_TLS_INCOMPAT_REASON
    # so a silent drift between the two guard call-sites fails loud.
    assert "websecure entrypoint + tls=true" in msg


def test_run_standalone_allows_no_https_when_standalone_chosen_at_prompt(
    tmp_path: Path,
) -> None:
    """Mirror coverage: the same interactive path with proxy='standalone' is
    a documented use case (local-only install, plain HTTP). Must not raise."""
    args = _args(
        work_dir=tmp_path,
        interactive=True,
        proxy_mode=None,
        enforce_https=False,
    )
    with patch(
        "webtrees_installer.flow.ask_choice",
        side_effect=["full", "standalone"],
    ), patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        exit_code = run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert exit_code == 0
    compose = yaml.safe_load((tmp_path / "compose.yaml").read_text())
    assert compose["services"]["phpfpm"]["environment"]["ENFORCE_HTTPS"] == "FALSE"


def test_run_standalone_allows_default_enforce_https_when_traefik_chosen_at_prompt(
    tmp_path: Path,
) -> None:
    """Wizard-default path: operator picks traefik at the prompt without
    passing --no-https (args.enforce_https is None). The new flow.py guard
    uses `is False`, so None must fall through and the stack must render
    with ENFORCE_HTTPS=TRUE (the wizard default)."""
    args = _args(
        work_dir=tmp_path,
        interactive=True,
        proxy_mode=None,
        enforce_https=None,
        domain="webtrees.example.com",
    )
    with patch(
        "webtrees_installer.flow.ask_choice",
        side_effect=["full", "traefik"],
    ):
        exit_code = run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert exit_code == 0
    compose = yaml.safe_load((tmp_path / "compose.yaml").read_text())
    assert compose["services"]["phpfpm"]["environment"]["ENFORCE_HTTPS"] == "TRUE"


def test_run_standalone_writes_admin_password_to_secrets_init(tmp_path: Path) -> None:
    """Compose.yaml must reference /secrets/wt_admin_password."""
    args = _args(work_dir=tmp_path)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=StringIO())

    compose_text = (tmp_path / "compose.yaml").read_text()
    assert "/secrets/wt_admin_password" in compose_text
    assert "WT_ADMIN_PASSWORD_FILE" in compose_text


def test_run_standalone_aborts_on_existing_file_without_force(tmp_path: Path) -> None:
    (tmp_path / "compose.yaml").write_text("# existing")
    args = _args(work_dir=tmp_path, force=False)

    with pytest.raises(PrereqError):
        run_standalone(args, stdin=StringIO(), stdout=StringIO())


def test_run_standalone_port_in_use_falls_back_to_fallback_port(tmp_path: Path) -> None:
    """Non-interactive flow: chosen port IN_USE → wizard bumps to the 28k fallback."""
    args = _args(work_dir=tmp_path, app_port=80)

    side_effects = iter([PortStatus.IN_USE, PortStatus.FREE])
    with patch("webtrees_installer.flow.probe_port", side_effect=lambda p: next(side_effects)):
        out = StringIO()
        exit_code = run_standalone(args, stdin=StringIO(), stdout=out)

    assert exit_code == 0
    compose_text = (tmp_path / "compose.yaml").read_text()
    # The standalone template renders ports as ${APP_PORT:-<chosen>}:80, so
    # the fallback bump shows up both as the .env override and as the inline
    # default. Match against the rendered substring rather than `28081:80`.
    assert "${APP_PORT:-28081}:80" in compose_text
    assert "APP_PORT=28081" in (tmp_path / ".env").read_text()


def test_run_standalone_fallback_port_in_use_short_circuits_without_redundant_probe(
    tmp_path: Path,
) -> None:
    """--port on the fallback that's already busy raises immediately, skipping the redundant retry."""
    args = _args(work_dir=tmp_path, app_port=28081)

    with patch(
        "webtrees_installer.flow.probe_port",
        return_value=PortStatus.IN_USE,
    ) as probe_mock:
        out = StringIO()
        with pytest.raises(PrereqError, match=r"port 28081 is in use; pass --port"):
            run_standalone(args, stdin=StringIO(), stdout=out)

    assert probe_mock.call_count == 1
    assert probe_mock.call_args.args == (28081,)
    assert "trying 28081 instead" not in out.getvalue()


def test_resolve_manifest_dir_raises_when_unset_and_default_missing(
    tmp_path: Path, monkeypatch
) -> None:
    """No env var + no in-image bake location → PrereqError with actionable hint."""
    monkeypatch.delenv("WEBTREES_INSTALLER_MANIFEST_DIR", raising=False)
    # Patch the canonical source of truth in versions.py; the flow.py
    # alias is a re-export, not a separate value, so patching it would
    # be a no-op.
    monkeypatch.setattr(
        "webtrees_installer.versions.DEFAULT_MANIFEST_DIR",
        tmp_path / "definitely-missing",
    )
    from webtrees_installer.flow import _resolve_manifest_dir
    with pytest.raises(PrereqError, match="MANIFEST_DIR"):
        _resolve_manifest_dir()


def test_resolve_manifest_dir_honours_env_var(monkeypatch, tmp_path: Path) -> None:
    """An explicit WEBTREES_INSTALLER_MANIFEST_DIR wins over the in-image default."""
    monkeypatch.setenv("WEBTREES_INSTALLER_MANIFEST_DIR", str(tmp_path))
    from webtrees_installer.flow import _resolve_manifest_dir
    assert _resolve_manifest_dir() == tmp_path


def test_run_standalone_invokes_bring_up_when_not_no_up(tmp_path: Path) -> None:
    """no_up=False → flow calls stack.bring_up."""
    args = _args(work_dir=tmp_path, no_up=False)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow.bring_up") as bring_up_mock:
        exit_code = run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert exit_code == 0
    bring_up_mock.assert_called_once()
    assert bring_up_mock.call_args.kwargs["work_dir"] == tmp_path


def test_run_standalone_propagates_stack_error(tmp_path: Path) -> None:
    """bring_up raising StackError bubbles out of run_standalone unmodified.

    The CLI layer is what catches StackError and converts it to exit 3 +
    stderr; the flow itself must not swallow the error and return 3, since
    that would force every caller (including future Phase 2b dev-flow) to
    re-implement the stderr routing.
    """
    from webtrees_installer.stack import StackError
    args = _args(work_dir=tmp_path, no_up=False)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow.bring_up", side_effect=StackError("boom")):
        with pytest.raises(StackError, match="boom"):
            run_standalone(args, stdin=StringIO(), stdout=StringIO())


def test_run_standalone_writes_demo_gedcom_when_demo_set(tmp_path: Path) -> None:
    """--demo true -> demo.ged is written next to compose.yaml."""
    args = _args(work_dir=tmp_path, demo=True, demo_seed=42)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        exit_code = run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert exit_code == 0
    gedcom = tmp_path / "demo.ged"
    assert gedcom.is_file()
    content = gedcom.read_text()
    assert content.startswith("0 HEAD")
    assert "2 VERS 5.5.1" in content


def test_run_standalone_skips_demo_when_demo_unset(tmp_path: Path) -> None:
    args = _args(work_dir=tmp_path, demo=False, demo_seed=42)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE):
        run_standalone(args, stdin=StringIO(), stdout=StringIO())

    assert not (tmp_path / "demo.ged").exists()


def test_run_standalone_imports_demo_when_not_no_up(tmp_path: Path) -> None:
    """no_up=False + --demo -> wizard calls _import_demo_tree."""
    args = _args(work_dir=tmp_path, demo=True, demo_seed=42, no_up=False)
    with patch("webtrees_installer.flow.probe_port", return_value=PortStatus.FREE), \
         patch("webtrees_installer.flow.bring_up"), \
         patch("webtrees_installer.flow._import_demo_tree") as import_mock:
        run_standalone(args, stdin=StringIO(), stdout=StringIO())

    import_mock.assert_called_once()


def test_compose_project_name_lowercases_and_strips(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Normalisation matches docker compose v2's project-name rules."""
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.delenv("COMPOSE_PROJECT_NAME", raising=False)

    # Canonical install path stays unchanged.
    canonical = tmp_path / "webtrees"
    canonical.mkdir()
    assert _compose_project_name(canonical) == "webtrees"

    # Mixed case + dots collapse to a compose-legal bucket.
    weird = tmp_path / "My.Webtrees"
    weird.mkdir()
    assert _compose_project_name(weird) == "mywebtrees"

    # Underscores and hyphens survive the strip pass.
    mixed = tmp_path / "Foo-Bar_baz"
    mixed.mkdir()
    assert _compose_project_name(mixed) == "foo-bar_baz"


def test_compose_project_name_honours_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """COMPOSE_PROJECT_NAME env wins over cwd basename and still normalises."""
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "Some.Custom-Name")
    assert _compose_project_name(tmp_path) == "somecustom-name"


def test_compose_project_name_preserves_symlink_basename(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Compose v2 derives its project name from the logical cwd basename
    (PWD env), NOT the realpath. The launchers use `basename "$(pwd)"`
    for the same reason. Calling `.resolve()` inside the wizard would
    desync the pre-seeded secrets volume from the volume compose mounts
    whenever the install path includes a symlink hop — e.g. user
    installs from /srv/webtrees -> /volume2/docker/foo: compose sees
    "webtrees", a `.resolve()`-based derivation would land on "foo".
    """
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.delenv("COMPOSE_PROJECT_NAME", raising=False)

    real = tmp_path / "foo"
    real.mkdir()
    link = tmp_path / "webtrees"
    link.symlink_to(real, target_is_directory=True)

    # The symlink path's logical basename is "webtrees"; .resolve()
    # would yield "foo". The helper must take the path as given.
    assert _compose_project_name(link) == "webtrees"


def test_compose_project_name_raises_when_work_dir_is_container_mount(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Inside the installer container the bind-mounted host directory
    becomes `/work`. Without COMPOSE_PROJECT_NAME the helper cannot tell
    what name compose will use on the host, so the pre-seeded secrets
    volume would land in `work_secrets` while compose mounts
    `<hostdir>_secrets`. Refuse to silently mismatch.
    """
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.delenv("COMPOSE_PROJECT_NAME", raising=False)
    with pytest.raises(PrereqError, match="COMPOSE_PROJECT_NAME is not set"):
        _compose_project_name(Path("/work"))


def test_compose_project_name_at_work_dir_with_explicit_env(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The /work guard only fires when COMPOSE_PROJECT_NAME is unset —
    with the env var the helper trusts the caller.
    """
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "mywebtrees")
    assert _compose_project_name(Path("/work")) == "mywebtrees"


def test_compose_project_name_raises_on_empty_normalisation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A basename of only stripped characters returns "" after
    normalisation, which would compose to leading-underscore volume
    names (`_secrets`, `_app`) — compose rejects those with a
    confusing error far from the root cause. Fail loud with a
    PrereqError that points at the input and the fix.
    """
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.delenv("COMPOSE_PROJECT_NAME", raising=False)
    weird = tmp_path / "!@#$%"
    weird.mkdir()
    with pytest.raises(PrereqError, match="empty after normalisation"):
        _compose_project_name(weird)


def test_compose_project_name_raises_on_empty_env_value(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A COMPOSE_PROJECT_NAME of only stripped characters also fails
    loud — the env var has the same compose-rejected outcome as a
    matching cwd basename, so the guard fires regardless of the source.
    """
    from webtrees_installer.flow import _compose_project_name

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "!@#$%")
    with pytest.raises(PrereqError, match="empty after normalisation"):
        _compose_project_name(tmp_path)


def test_list_surviving_volumes_translates_docker_failure_to_prereq_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A docker-daemon failure on `docker volume ls` must not leak past
    the exit-code translator. The volume scan wraps subprocess.run in
    try/except so cli.py's _run_with_exit_codes can translate it into
    a clean exit 2 with the daemon's stderr.

    Uses the module-top `real_list_surviving_volumes` alias to bypass
    the autouse fixture's `_list_surviving_volumes` mock — the alias
    was captured before the patch swapped the attribute on the flow
    module."""
    import subprocess

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "mywebtrees")
    fake_failure = subprocess.CalledProcessError(
        returncode=1,
        cmd=["docker", "volume", "ls"],
        stderr="Cannot connect to the Docker daemon at unix:///var/run/docker.sock",
    )
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_list_surviving_volumes(tmp_path)

    msg = str(exc_info.value)
    assert "failed to list docker volumes" in msg
    assert "mywebtrees" in msg
    assert "Cannot connect to the Docker daemon" in msg


def test_wipe_volumes_noop_on_empty_list() -> None:
    """An empty volume list is a fast no-op: the caller did not even
    bother to call us if there was nothing to wipe."""
    # Real function via module-top alias; the autouse fixture does not
    # patch _wipe_volumes so the bypass is precautionary here.
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=AssertionError("subprocess.run must not be called"),
    ):
        real_wipe_volumes([])


def test_wipe_volumes_translates_docker_failure_to_prereq_error() -> None:
    """A docker-daemon failure on EVERY `docker volume rm -f` invocation
    surfaces all volumes in the PrereqError. Per-volume iteration means
    each name gets its own line; the wrap collects them rather than
    short-circuiting on the first failure."""
    import subprocess

    fake_failure = subprocess.CalledProcessError(
        returncode=1,
        cmd=["docker", "volume", "rm", "-f"],
        stderr="Error response from daemon: volume is in use",
    )
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_wipe_volumes(["mywebtrees_database", "mywebtrees_secrets"])

    msg = str(exc_info.value)
    assert "failed to remove the following docker volumes" in msg
    assert "mywebtrees_database" in msg
    assert "mywebtrees_secrets" in msg
    assert "volume is in use" in msg
    assert "docker compose -p <project> down -v" in msg


def test_wipe_volumes_collects_partial_failures_without_aborting() -> None:
    """Per-volume iteration: a held-by-sibling-stack volume fails its
    own rm without short-circuiting the rest. The caller still gets a
    PrereqError so they know cleanup is incomplete, but only the
    actually-stuck volumes show up — the successfully-wiped ones
    aren't in the list (so the operator doesn't try to clean up state
    that's already gone)."""
    import subprocess

    # First call succeeds, second fails (held by sibling stack),
    # third succeeds. Exercises the iterate-and-collect path.
    fake_failure = subprocess.CalledProcessError(
        returncode=1,
        cmd=["docker", "volume", "rm", "-f", "mywebtrees_database"],
        stderr="Error response from daemon: volume is in use",
    )
    completed = subprocess.CompletedProcess(args=[], returncode=0, stdout="", stderr="")
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=[completed, fake_failure, completed],
    ), pytest.raises(PrereqError) as exc_info:
        real_wipe_volumes(
            ["mywebtrees_secrets", "mywebtrees_database", "mywebtrees_app"]
        )

    msg = str(exc_info.value)
    assert "mywebtrees_database" in msg
    assert "volume is in use" in msg
    # The two volumes that succeeded must NOT show up in the failure
    # list — they're already gone and re-listing them would mislead
    # the operator.
    assert "mywebtrees_secrets" not in msg
    assert "mywebtrees_app" not in msg


def test_wipe_volumes_succeeds_silently_when_every_call_succeeds() -> None:
    """All three volumes wipe cleanly — no exception, three subprocess
    calls observed."""
    import subprocess

    completed = subprocess.CompletedProcess(args=[], returncode=0, stdout="", stderr="")
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=[completed, completed, completed],
    ) as run_mock:
        real_wipe_volumes(["mywebtrees_secrets", "mywebtrees_database", "mywebtrees_app"])

    assert run_mock.call_count == 3


def test_list_surviving_volumes_translates_missing_docker_binary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Subprocess can fail BEFORE docker even runs — FileNotFoundError
    when the binary isn't on PATH, PermissionError when the exec bit
    is dropped or the socket refuses connect. These are OSError, NOT
    CalledProcessError, so the wrap must catch both classes."""
    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "mywebtrees")
    fake_failure = FileNotFoundError(2, "No such file or directory", "docker")
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_list_surviving_volumes(tmp_path)

    msg = str(exc_info.value)
    assert "failed to list docker volumes" in msg
    assert "No such file or directory" in msg
    assert "docker" in msg


def test_wipe_volumes_translates_missing_docker_binary() -> None:
    """Same OSError bypass as the list helper — wrap must catch it."""
    fake_failure = PermissionError(13, "Permission denied", "/usr/bin/docker")
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_wipe_volumes(["mywebtrees_database"])

    msg = str(exc_info.value)
    assert "failed to remove the following docker volumes" in msg
    assert "Permission denied" in msg


def test_list_surviving_volumes_coerces_bytes_stderr_to_utf8(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Defensive: a future call site that drops `text=True` would hand
    back bytes stderr. The detail-extractor must decode (replace mode)
    rather than leak a `b'...'` literal into the PrereqError message."""
    import subprocess

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "mywebtrees")
    fake_failure = subprocess.CalledProcessError(
        returncode=1,
        cmd=["docker"],
        stderr=b"Cannot connect to the Docker daemon",
    )
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_list_surviving_volumes(tmp_path)

    msg = str(exc_info.value)
    assert "Cannot connect to the Docker daemon" in msg
    assert "b'" not in msg  # no bytes-literal leak


@pytest.mark.parametrize("stderr_value", ["", "   ", None])
def test_list_surviving_volumes_falls_back_when_subprocess_emits_no_stderr(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
    stderr_value: str | None,
) -> None:
    """When stderr is empty / whitespace / None, _extract_subprocess_detail
    falls back to `str(exc)` (CalledProcessError's default representation
    carries the command + exit code, which is informative enough for the
    operator). The message must never end in a bare `failed: ` with no
    body."""
    import subprocess

    monkeypatch.setenv("COMPOSE_PROJECT_NAME", "mywebtrees")
    fake_failure = subprocess.CalledProcessError(
        returncode=1, cmd=["docker", "volume", "ls"], stderr=stderr_value,
    )
    with patch(
        "webtrees_installer.flow.subprocess.run",
        side_effect=fake_failure,
    ), pytest.raises(PrereqError) as exc_info:
        real_list_surviving_volumes(tmp_path)

    msg = str(exc_info.value)
    # Either str(exc)'s default "returned non-zero exit status" boilerplate
    # OR the ultimate "<no detail>" fallback — never an empty tail.
    assert "failed to list docker volumes" in msg
    assert msg.rstrip().split(":")[-1].strip() != ""
    assert "returned non-zero exit status" in msg or "<no detail>" in msg


def test_compute_stage_total_no_up_only_render() -> None:
    """--no-up skips bring_up and demo-import → only render stage runs."""
    from webtrees_installer.flow import _compute_stage_total
    assert _compute_stage_total(no_up=True, demo=False) == 1
    assert _compute_stage_total(no_up=True, demo=True) == 1, (
        "demo flag is meaningless under --no-up (no stack to import into); "
        "must not add a phantom stage to the [N/M] denominator"
    )


def test_compute_stage_total_bringing_up_without_demo() -> None:
    from webtrees_installer.flow import _compute_stage_total
    assert _compute_stage_total(no_up=False, demo=False) == 2


def test_compute_stage_total_full_with_demo() -> None:
    from webtrees_installer.flow import _compute_stage_total
    assert _compute_stage_total(no_up=False, demo=True) == 3
