name: webtrees

volumes:
    app:
    media:
    database:

services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD
            - MARIADB_HOST
            - MARIADB_PORT
            - MARIADB_DATABASE
            - MARIADB_USER
            - MARIADB_PASSWORD
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - default

    phpfpm:
        depends_on:
            - db
        build:
            context: .
            dockerfile: ./Dockerfile
            target: php-build
            args:
                - PHP_VERSION
        image: ${DOCKER_SERVER}/webtrees/php:${PHP_VERSION}
        environment:
            - ENVIRONMENT
            - ENFORCE_HTTPS
            - PHP_MAX_EXECUTION_TIME
            - PHP_MAX_INPUT_VARS
            - PHP_MEMORY_LIMIT
            - PHP_POST_MAX_SIZE
            - PHP_UPLOAD_MAX_FILESIZE
            - MAIL_SMTP
            - MAIL_DOMAIN
            - MAIL_HOST
        restart: unless-stopped
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - app:/var/www
            - media:/var/www/public/data/media
        networks:
            - default

    nginx:
        depends_on:
            - phpfpm
        image: nginx:stable-alpine
        environment:
            - ENFORCE_HTTPS
        restart: unless-stopped
        volumes:
            - app:/var/www:ro
            - media:/var/www/public/data/media:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./rootfs/etc/nginx/templates:/etc/nginx/templates:ro
            - ./rootfs/etc/nginx/includes/enforce-https.conf:/etc/nginx/includes/enforce-https.conf:ro
            - ./rootfs/etc/nginx/includes/php-proxy.conf:/etc/nginx/includes/php-proxy.conf:ro
            - ./rootfs/etc/nginx/includes/security-headers-map.conf:/etc/nginx/includes/security-headers-map.conf:ro
            - ./rootfs/etc/nginx/includes/security-headers.conf:/etc/nginx/includes/security-headers.conf:ro
            - ./rootfs/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - default

    pma:
        depends_on:
            - db
        image: phpmyadmin:latest
        restart: unless-stopped
        environment:
            PMA_HOST: ${MARIADB_HOST}
            PMA_PORT: ${MARIADB_PORT}
            UPLOAD_LIMIT: ${UPLOAD_LIMIT}
            MEMORY_LIMIT: 512M
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - default

networks:
    default:
