FROM php:8.3-fpm-alpine

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions curl ctype dom exif fileinfo gd iconv imagick intl json opcache mbstring pcre pdo pdo_mysql session simplexml xdebug xml zip zlib

# Copy opcache configuration
COPY php/conf.d/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
