volumes:
    media:
        driver: local
        driver_opts:
            type: none
            device: ${MEDIA_DIR}
            o: bind

# Add services to the database network
services:
    db:
        # Stop the local database
        entrypoint: /bin/bash
        command: -c "exit 0"
        restart: no

    buildbox:
        networks:
            - database

    buildbox-root:
        networks:
            - database

    phpfpm:
        networks:
            - database

    nginx:
        networks:
            - database

    pma:
        networks:
            - database

networks:
    # Database network
    database:
        external: true
        name: ${MARIADB_HOST}
