volumes:
    app:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/app
            o: bind
    media:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/persistent/media
            o: bind
    database:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/persistent/database
            o: bind

x-buildbox-base: &buildbox-base
    build:
        context: .
        dockerfile: ./Dockerfile
        target: build-box
        args:
            - PHP_VERSION
            - DOCKER_SERVER
    image: ${DOCKER_SERVER}/webtrees/buildbox:${PHP_VERSION}
    depends_on:
        - db
        - phpfpm
    working_dir: /var/webtrees
    env_file:
        - .env
    environment:
        - SSH_AUTH_SOCK=/tmp/ssh.sock
        - TERM=xterm-256color
    volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - ./:/var/webtrees
        - ${HOME}/.ssh:/root/.ssh
        - ${SSH_AUTH_SOCK}:/tmp/ssh.sock
    networks:
        - default

services:
    db:
        volumes:
            - database:/var/lib/mysql

    buildbox-root:
        <<: *buildbox-base
        entrypoint: "/opt/root-entrypoint.sh"
        environment:
            - COMPOSER_AUTH

    buildbox:
        <<: *buildbox-base

    nginx:
        # Add a port to access the website via IP. For example, 50010 is an available external port
        # mapped to internal docker container port 80.
        ports:
            - "50010:80"

    pma:
        environment:
            PMA_USER: ${MARIADB_USER}
            PMA_PASSWORD: ${MARIADB_PASSWORD}
