#!/usr/bin/env bash

# Instructs a shell to exit if a command fails, i.e., if it outputs a non-zero exit status.
set -e

## Prints out command arguments during execution.
#set -x

source scripts/configuration

# Main execution
main() {
    validateEnvironment
    setupConfiguration
    logSuccess "Configuration successfully applied"
}

main
