#!/usr/bin/env bash
#
# Regenerate templates/portainer/{compose.yaml,.env.example} from the
# installer's Jinja templates. Operators don't run this — it's a
# release-time helper so the static files Portainer imports stay in
# lock-step with what the wizard produces.
#
# Usage:
#   ./scripts/render-portainer-templates.sh
#
# Inputs:
#   installer/webtrees_installer/templates/{compose.standalone.j2,env.j2,Makefile.j2}
#   dev/versions.json (manifest dir for the catalog)
#
# Outputs:
#   templates/portainer/compose.yaml
#   templates/portainer/.env.example
#
# The render uses the standalone proxy mode with --edition full,
# --port 28080, ENFORCE_HTTPS=TRUE, pretty-urls off, no admin bootstrap.
# This is the most common Portainer scenario: a self-hosted family
# tree behind a reverse proxy the operator already has set up at the
# Portainer host. Operators who need different defaults edit the env
# vars in Portainer's stack UI.
#
# `render_files()` also writes a third artefact (Makefile) into the
# tempdir; we deliberately drop it because Portainer's stack-deploy
# flow has no use for it (operators run docker compose via Portainer's
# UI, not via the embedded Makefile shortcuts). If a future installer
# version adds a fourth artefact relevant to Portainer, surface it
# explicitly here rather than relying on the tempdir cleanup to mask
# the gap.

set -o errexit -o nounset -o pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/templates/portainer"
mkdir -p "$OUT"

# Non-editable install (no `-e`, no `[test]` extras) so the host's
# installer/ tree stays clean and the docker step pulls the minimum
# dependency closure. Bind the installer dir read-only and copy it
# into a writable container path before `pip install`: setuptools'
# build backend needs to write the .egg-info / build/ directories,
# but doing so on the host tree dirties the worktree with untracked
# files that confuse the `git diff templates/portainer/` review step.
docker run --rm \
    -v "$ROOT/installer:/app-src:ro" \
    -v "$ROOT/dev:/dev-cfg:ro" \
    -v "$OUT:/out" \
    -e "WEBTREES_INSTALLER_MANIFEST_DIR=/dev-cfg" \
    python:3.13-slim sh -c '
        cp -r /app-src /app
        cd /app
        # Keep pip stdout quiet but route stderr through so a network
        # outage / broken pyproject surfaces with context instead of a
        # downstream opaque ModuleNotFoundError.
        if ! pip install --no-cache-dir --quiet . >/dev/null; then
            printf "pip install failed; check network + installer/pyproject.toml above\n" >&2
            exit 1
        fi
        python -c "
from datetime import datetime, timezone
from pathlib import Path
import tempfile, shutil
from webtrees_installer.render import RenderInput, render_files
from webtrees_installer.versions import load_catalog, resolve_manifest_dir
catalog = load_catalog(resolve_manifest_dir())
ri = RenderInput(
    edition=\"full\",
    proxy_mode=\"standalone\",
    app_port=28080,
    domain=None,
    admin_bootstrap=False,
    admin_user=None,
    admin_email=None,
    catalog=catalog,
    generated_at=datetime(2026, 5, 15, tzinfo=timezone.utc),
    enforce_https=True,
    pretty_urls=False,
)
with tempfile.TemporaryDirectory() as t:
    render_files(input_model=ri, target_dir=Path(t))
    shutil.copy(Path(t)/\"compose.yaml\", \"/out/compose.yaml\")
    shutil.copy(Path(t)/\".env\", \"/out/.env.example\")
"
'

# Rewrite the timestamp comment to a placeholder. The installer bakes
# `generated_at` into the .env header for traceability when a user
# runs it interactively, but for the pre-rendered Portainer template
# the fixed date misleads operators reading it months later — they
# read it as "installer untouched since May 2026" when really the
# date is just the script-rendered constant.
sed -i \
    -E 's|^# Generated by webtrees-installer .* on .*$|# Pre-rendered Portainer template — regenerated by scripts/render-portainer-templates.sh.|' \
    "$OUT/.env.example"

# Post-condition: a regex drift in env.j2's header would let the sed
# above silently no-op, re-introducing the misleading-timestamp nit
# this script was specifically taught to scrub. Fail loud if the
# expected replacement isn't visible — cheaper than re-discovering
# the bug via a confused operator report.
if ! grep -q '^# Pre-rendered Portainer template' "$OUT/.env.example"; then
    printf 'render-portainer-templates: env header rewrite did not take — installer env.j2 may have drifted.\n' >&2
    exit 1
fi

printf 'Regenerated templates/portainer/compose.yaml + .env.example.\n'
printf 'Review the diff and commit if intentional.\n'
