#!/usr/bin/env bash

# Instructs a shell to exit if a command fails, i.e., if it outputs a non-zero exit status.
set -e

## Prints out command arguments during execution.
#set -x

source scripts/configuration

# Create directories before mounting
DIRS=(
    "${APP_DIR}"
    "./setup"
    "$APP_DIR/public"
    "$APP_DIR/vendor"
)

echo -e "\033[0;34m[+] Change permissions for APP_DIR: ${APP_DIR}\033[0m"

# Create directories with proper permissions
for dir in "${DIRS[@]}"; do
    mkdir -p $dir
done

# Set ownership and permissions for directories
USER=${LOCAL_USER_ID}
GROUP=${LOCAL_GROUP_ID}

chown -R ${USER}:${GROUP} ${DIRS[*]}
chmod -R ug+rw ${DIRS[*]}

rm -rf "$APP_DIR/html"

# Copy public folder to webtrees directory
ln -s public "$APP_DIR/html"

logSuccess "Permissions changed successfully"
