#!/usr/bin/env bash

cd "$(dirname $0)/.."

echo "Setting up webtrees development environment"

if [ -f ".env" ]; then
    echo "Environment file already exists. Skipping."
    exit 0;
fi

if [ ! -f ".env.dist" ]; then
    echo "Environment file .env.dist does not exist. Aborting."
    exit 1;
fi

if [ ! -d "persistent/database" ]; then
    mkdir -p "persistent/database"
fi

echo "Copying .env.dist to .env"
cp .env.dist .env

HOSTNAME=$(hostname)
echo "Set COMPOSE_FILE"
if [ "$HOSTNAME" == "sobol" ]; then
    pattern="s/COMPOSE_FILE=.*/COMPOSE_FILE=docker-compose.yaml\:docker-compose.development.yaml\:docker-compose.traefik.yaml\:docker-compose.local.yaml/"
    sed -i "${pattern}" .env
else
    pattern="s/COMPOSE_FILE=.*/COMPOSE_FILE=docker-compose.yaml\:docker-compose.development.yaml/"
    sed -i "${pattern}" .env
fi

read -p "Enter your MySQL/MariaDB root password: " MARIADB_ROOT_PASSWORD
pattern="s/MARIADB_ROOT_PASSWORD=.*/MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}/"
sed -i "${pattern}" .env

read -p "Enter your MySQL/MariaDB password: " MARIADB_ROOT_PASSWORD
pattern="s/MARIADB_PASSWORD=.*/MARIADB_PASSWORD=${MARIADB_ROOT_PASSWORD}/"
sed -i "${pattern}" .env

echo "Set local UID"
pattern="s/LOCAL_UID=.*/LOCAL_UID=$(id -u)/"
sed -i "${pattern}" .env

echo "Set local username"
pattern="s/LOCAL_USER_NAME=.*/LOCAL_USER_NAME=$(whoami | sed 's/\./-/')/"
sed -i "${pattern}" .env

echo "Set GIT username"
pattern="s/GIT_AUTHOR_NAME=.*/GIT_AUTHOR_NAME=$(git config user.name)/"
sed -i "${pattern}" .env

echo "Set GIT email"
pattern="s/GIT_AUTHOR_EMAIL=.*/GIT_AUTHOR_EMAIL=$(git config user.email)/"
sed -i "${pattern}" .env

echo "Run install"
bash -c "docker compose pull"
make install

echo "Development environment setup complete."
echo "You can now start the development environment with 'make up'"
